
version: '3.0'
services:
  interactive:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID}
        - USER_NAME=${USER_NAME}
    ports:
      - ${APPLICATION_PORT}:5000
    container_name: erik-container
    image: ${PROJ_NAME}-image
    user: ${USER_ID}:${USER_ID}
    stdin_open: true
    tty: true
    command: bash
    volumes:
      - ../app:/app
